const OFFICIAL_URL='https://top.meitetsu.co.jp/em/train_emtop.asp';
const lines={
 main:{name:'名古屋本線',crew:'名古屋乗務区',color:'#c40018',stations:['豊橋','伊奈','国府','本宿','東岡崎','新安城','知立','鳴海','神宮前','金山','名鉄名古屋','須ケ口','一宮','笠松','名鉄岐阜']},
 inuyama:{name:'犬山線',crew:'犬山乗務区',color:'#0075c9',stations:['名鉄名古屋','栄生','上小田井','西春','岩倉','江南','柏森','扶桑','犬山']},
 tokoname:{name:'常滑線・空港線',crew:'神宮前乗務区',color:'#009a9a',stations:['神宮前','大江','太田川','朝倉','新舞子','常滑','りんくう常滑','中部国際空港']},
 kowa:{name:'河和線',crew:'神宮前乗務区',color:'#ef7b00',stations:['太田川','高横須賀','南加木屋','巽ケ丘','阿久比','知多半田','青山','河和']},
 tsushima:{name:'津島線',crew:'名古屋乗務区',color:'#7c49a5',stations:['須ケ口','甚目寺','七宝','木田','青塚','勝幡','藤浪','津島']},
 mikawa:{name:'三河線',crew:'知立乗務区',color:'#006b3f',stations:['知立','重原','刈谷','刈谷市','小垣江','三河高浜','高浜港','碧南']},
 nishio:{name:'西尾線',crew:'知立乗務区',color:'#b00062',stations:['新安城','南安城','桜井','米津','西尾','福地','吉良吉田']},
 seto:{name:'瀬戸線',crew:'瀬戸運輸区',color:'#008c45',stations:['栄町','東大手','清水','大曽根','小幡','喜多山','大森・金城学院前','尾張旭','三郷','新瀬戸','尾張瀬戸']}
};
// スクリーンショットに近いレイアウトで表示する列車番号データ。実運行データではありません。
const trainDatabase={
 '1980S':{type:'普通',code:'M',cars:2,crew:'名古屋乗務区',route:'尾西線',origin:'一宮',destination:'津島',notice:'自動放送　[221]',state:'乗務開始',stops:[
  ['一宮','19:14:00','19:14:00'],['観音','19:16:20','19:16:50'],['苅安','19:18:30','19:19:00'],['二子','19:20:40','19:21:10'],['萩原','19:22:50','19:28:10'],['玉野','19:29:55','19:30:25'],['山崎','19:32:10','19:32:40'],['森上','19:34:30','19:36:30'],['上丸','19:38:40','19:39:10'],['丸渕','19:40:50','19:41:20'],['渕高','19:42:50','19:43:20'],['六輪','19:45:00','19:45:30'],['町方','19:47:25','19:47:55'],['津島','19:50:10',''] ]},
 '1800M':{type:'普通',code:'M',cars:2,origin:'豊橋',destination:'名鉄岐阜',notice:'自動放送　[101]',state:'乗務開始',stops:[['豊橋','18:00:00','18:01:00'],['国府','18:10:00','18:10:30'],['東岡崎','18:23:00','18:23:30'],['知立','18:35:00','18:35:30'],['金山','18:55:00','18:55:30'],['名鉄名古屋','18:59:00','18:59:30'],['一宮','19:14:00','19:14:30'],['笠松','19:24:00','19:24:30'],['名鉄岐阜','19:30:00',''] ]},
 '2100I':{type:'急行',code:'I',cars:6,origin:'名鉄名古屋',destination:'犬山',notice:'自動放送　[305]',state:'運転中',stops:[['名鉄名古屋','21:00:00','21:00:30'],['上小田井','21:07:00','21:07:30'],['岩倉','21:17:00','21:17:30'],['江南','21:24:00','21:24:30'],['柏森','21:31:00','21:31:30'],['犬山','21:40:00','']]}
};
let officialData=null;
let officialDataPromise=null;
const OFFICIAL_TIMETABLE_URL='https://www.meitetsu.co.jp/train/timetable/';
function isHolidaySchedule(d=new Date()){ const day=d.getDay(); return day===0||day===6; }
function normalizeTrainNo(q){return String(q||'').trim().toUpperCase().replace(/\s+/g,'').replace(/[＊*]$/,'');}
async function loadOfficialData(){
  if(officialDataPromise)return officialDataPromise;
  officialDataPromise=fetch('./data/timetables.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('timetable data missing');return r.json()}).then(d=>{officialData=d; const el=$('dataStatus'); if(el){el.className='data-status ok';el.textContent=`公式PDF解析データ：${d.trains?.length||0}列車・${d.timetableRevision||'—'}改正`; } return d}).catch(e=>{officialData=null; const el=$('dataStatus'); if(el){el.className='data-status warn';el.textContent='公式解析データ未配置：GitHub Actionsで「時刻表データ更新」を実行してください。';} return null});
  return officialDataPromise;
}
function findOfficialTrain(q){
  if(!officialData?.trains)return null;
  const n=normalizeTrainNo(q);
  const all=officialData.trains.filter(t=>normalizeTrainNo(t.no)===n);
  if(!all.length)return null;
  const wanted=isHolidaySchedule()?'holiday':'weekday';
  return all.find(t=>t.day===wanted)||all[0];
}
function crewForRoute(route){
  const r=String(route||'');
  if(/瀬戸/.test(r)) return '瀬戸運輸区';
  if(/犬山|各務原|広見|小牧/.test(r)) return '犬山乗務区';
  if(/常滑|空港|河和|知多新/.test(r)) return '神宮前乗務区';
  if(/三河|豊田|西尾|蒲郡/.test(r)) return '知立乗務区';
  if(/名古屋本線|豊川|津島|尾西|竹鼻|羽島/.test(r)) return '名古屋乗務区';
  return line()?.crew || '名古屋乗務区';
}

function officialToDetail(t,q){
  const stops=(t.stops||[]).filter(x=>x&&x[0]&&x[1]).map(x=>[x[0],x[1],x[1]]);
  const origin=stops[0]?.[0]||'—';
  const destination=t.destination||stops.at(-1)?.[0]||'—';
  const code=({名古屋本線:'M','犬山線・各務原線':'IY','瀬戸線':'S','津島線':'T','尾西線':'BS','常滑線・空港線・河和線・知多新線':'T','三河線':'M','西尾線・蒲郡線':'N'})[t.route]||'—';
  return {type:t.type||'—',code,cars:'—',crew:crewForRoute(t.route),origin,destination,notice:`名鉄公式路線別時刻表 PDF解析 / ${t.day==='holiday'?'土・休日':'平日'} / ${t.route}`,state:'時刻表',stops,no:q,source:t.pdf,route:t.route,day:t.day};
}
let state={line:'main',stationIndex:0,direction:'up',type:'普通',dark:false,seconds:true,auto:true,delay:false,cancel:false,notify:false,zoom:1,favorites:[],view:'schedule',detail:null};
const $=id=>document.getElementById(id);const pad=n=>String(n).padStart(2,'0');const now=()=>new Date();const timeStr=(d,sec=true)=>`${pad(d.getHours())}:${pad(d.getMinutes())}${sec?':'+pad(d.getSeconds()):''}`;
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>e.classList.remove('show'),2300)}
function save(){localStorage.setItem('meitetsuDemoV4',JSON.stringify({...state,detail:null}))}function load(){try{Object.assign(state,JSON.parse(localStorage.getItem('meitetsuDemoV4')||'{}'))}catch(e){}}
const line=()=>lines[state.line];
function initSelectors(){$('lineSelect').innerHTML=Object.entries(lines).map(([k,v])=>`<option value="${k}">${v.name}</option>`).join('');$('lineSelect').value=state.line;fillStations();$('directionSelect').value=state.direction;$('typeSelect').value=state.type;$('darkToggle').checked=state.dark;$('secondsToggle').checked=state.seconds;$('autoRefresh').checked=state.auto;$('notifyToggle').checked=state.notify;renderQuick()}
function fillStations(){const l=line();$('stationSelect').innerHTML=l.stations.map((s,i)=>`<option value="${i}">${s}</option>`).join('');state.stationIndex=Math.min(Math.max(state.stationIndex,0),l.stations.length-1);$('stationSelect').value=state.stationIndex}
function renderQuick(){$('quickLines').innerHTML=Object.entries(lines).map(([k,v])=>`<button class="quick ${k===state.line?'active':''}" data-line="${k}"><i style="background:${v.color}"></i>${v.name}</button>`).join('');document.querySelectorAll('.quick').forEach(b=>b.onclick=()=>setLine(b.dataset.line))}
function setLine(k){state.line=k;state.stationIndex=0;$('lineSelect').value=k;fillStations();renderQuick();update()}
function trainForLine(){const l=line(),origin=state.direction==='up'?l.stations[0]:l.stations.at(-1),destination=state.direction==='up'?l.stations.at(-1):l.stations[0],code={main:'M',seto:'S',inuyama:'I',tokoname:'T',kowa:'K',tsushima:'T',mikawa:'M',nishio:'N'}[state.line]||'L',cars={普通:2,準急:4,急行:6,快速特急:8}[state.type]||2;return{origin,destination,code,cars,no:`${1800+state.stationIndex}${code}S`}}
function scheduleTimes(){const l=line(),start=state.direction==='up'?0:l.stations.length-1,d=now(),base=Math.floor((d.getHours()*60+d.getMinutes())/20)*20+20,speed={普通:5,準急:4,急行:3,快速特急:2}[state.type]||5;return l.stations.map((name,i)=>{const dist=Math.abs(i-start),min=base+dist*speed;return{name,idx:i,minutes:min,arrival:`${pad(Math.floor(min/60)%24)}:${pad(min%60)}`,departure:`${pad(Math.floor(min/60)%24)}:${pad((min+1)%60)}`}})}
function currentIndex(){const l=line(),d=now(),cur=d.getHours()*60+d.getMinutes()+d.getSeconds()/60;let idx=Math.floor((cur-(5*60+30))/20);idx=Math.max(0,Math.min(l.stations.length-1,idx));return state.direction==='up'?idx:l.stations.length-1-idx}
function renderHeader(){const t=trainForLine();$('trainType').textContent=state.type;$('serviceCode').textContent=t.code;$('cars').textContent=t.cars+'両';$('origin').textContent=t.origin;$('destination').textContent=t.destination;$('trainNo').textContent=t.no;$('metricStation').textContent=line().stations[state.stationIndex];$('metricLine').textContent=line().name;document.documentElement.style.setProperty('--line-accent',line().color)}
function renderMap(){const times=scheduleTimes(),ci=currentIndex();$('routeMap').innerHTML=times.map((x,i)=>{const cls=i<ci?'passed':i===ci?'current':'';return`<div class="map-stop ${cls}"><div class="map-dot"></div><div class="map-label">${x.name}</div><div class="map-time">${x.departure}</div></div>`}).join('')}
function renderSchedule(){const times=scheduleTimes(),ci=currentIndex();$('scheduleTable tbody').innerHTML=times.map((x,i)=>{const st=i<ci?'<span class="state done">通過</span>':i===ci?'<span class="state now">停車中</span>':'<span class="state">予定</span>',fav=state.favorites.includes(x.name)?'★':'☆';return`<tr class="${i===ci?'current':''}"><td><button class="station-link" data-index="${i}">${x.name}</button></td><td>${x.arrival}</td><td>${x.departure}</td><td>${st}</td><td><button class="star-btn" data-station="${x.name}">${fav}</button></td></tr>`}).join('');document.querySelectorAll('.station-link').forEach(b=>b.onclick=()=>{state.stationIndex=+b.dataset.index;$('stationSelect').value=state.stationIndex;update()});document.querySelectorAll('.star-btn').forEach(b=>b.onclick=()=>toggleFavorite(b.dataset.station));const pos=times[ci],next=times[Math.min(ci+1,times.length-1)];$('currentLocation').textContent=`現在位置：${pos?.name||'—'}`;$('nextStop').textContent=`次駅：${next?.name||'—'}`;$('eta').textContent=next?`次駅まで ${Math.max(0,Math.round(next.minutes-(now().getHours()*60+now().getMinutes()+now().getSeconds()/60)))}分`:'到着 —';$('metricPosition').textContent=pos?.name||'—'}
function renderNext(){const l=line(),station=state.stationIndex,base=now(),types=['普通','準急','急行','快速特急'];let html='';for(let k=0;k<5;k++){const d=new Date(base.getTime()+(k*8+3+station%4)*60000),typ=types[(k+station)%types.length];html+=`<div class="next-item"><div class="next-time">${timeStr(d,false)}</div><div class="next-main"><strong>${typ}</strong><small>${state.direction==='up'?l.stations.at(-1):l.stations[0]} 行</small></div><span class="next-tag">${{普通:'2',準急:'4',急行:'6',快速特急:'8'}[typ]}両</span></div>`}$('nextTrains').innerHTML=html;const first=new Date(base.getTime()+(3+station%4)*60000);$('metricNext').textContent=timeStr(first,false);$('metricCountdown').textContent=`あと ${Math.max(0,Math.ceil((first-base)/60000))}分`}
function renderTimetable(){const st=line().stations[state.stationIndex],base=now(),types=['普通','準急','急行'];$('timetableTitle').textContent=st+'駅';let html='';for(let i=0;i<12;i++){const d=new Date(base.getTime()+(i+2)*7*60000),typ=types[(i+state.stationIndex)%3],dest=state.direction==='up'?line().stations.at(-1):line().stations[0];html+=`<div class="tt-row"><strong>${timeStr(d,false)}</strong><span class="tt-type">${typ}</span><span>${dest} 行</span><em>${i%4===0?'おすすめ':' '}</em></div>`}$('timetableList').innerHTML=html}
function renderFavorites(){const fav=[...new Set(state.favorites)];$('metricFav').textContent=fav.length;$('favoritesList').innerHTML=fav.length?fav.map(s=>`<button class="favorite-chip" data-fav="${s}">★ ${s}</button>`).join(''):'<div class="empty">お気に入り駅はありません</div>';document.querySelectorAll('.favorite-chip').forEach(b=>b.onclick=()=>{for(const [k,l] of Object.entries(lines)){const i=l.stations.indexOf(b.dataset.fav);if(i>=0){state.line=k;state.stationIndex=i;break}}$('lineSelect').value=state.line;fillStations();renderQuick();update()});$('favoriteStation').textContent=state.favorites.includes(line().stations[state.stationIndex])?'★ 保存済み':'☆ 駅を保存'}
function toggleFavorite(name){const i=state.favorites.indexOf(name);if(i>=0){state.favorites.splice(i,1);toast(name+'をお気に入りから削除')}else{state.favorites.push(name);toast(name+'をお気に入りに追加')}renderFavorites();renderSchedule();save()}
function renderNews(){const n=[];if(state.delay)n.push(['遅延','一部列車に遅れが発生しています（デモ）']);if(state.cancel)n.push(['運休','一部列車を運休として表示しています（デモ）']);if(!n.length)n.push(['運行情報','現在、アプリ内は平常運転表示です。']);n.push(['案内','実際の運行情報は名鉄公式サイトをご確認ください。']);$('newsList').innerHTML=n.map(x=>`<div class="news-item"><strong>${x[0]}</strong><small>${x[1]}</small></div>`).join('')}
function renderBanner(){const dot=document.querySelector('.status-dot');if(state.cancel||state.delay){dot.className='status-dot warn';$('bannerTitle').textContent=state.cancel?'運休情報あり（デモ）':'遅延情報あり（デモ）';$('bannerText').textContent='このアプリ内のシミュレーション状態です。実際の運行状況ではありません。'}else{dot.className='status-dot ok';$('bannerTitle').textContent='平常運転';$('bannerText').textContent='このアプリ内の運行情報はデモ表示です。'}}
function renderClock(){const d=now();$('digital').textContent=timeStr(d,state.seconds);$('dateText').textContent=d.toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'short'});drawClock($('analog'),d)}
function drawClock(c,d){const ctx=c.getContext('2d'),r=c.width/2;ctx.clearRect(0,0,c.width,c.height);ctx.save();ctx.translate(r,r);ctx.beginPath();ctx.arc(0,0,r-5,0,Math.PI*2);ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--panel');ctx.fill();ctx.strokeStyle=getComputedStyle(document.body).getPropertyValue('--line');ctx.lineWidth=4;ctx.stroke();for(let i=0;i<60;i++){let a=i*Math.PI/30;ctx.save();ctx.rotate(a);ctx.beginPath();ctx.moveTo(0,-r+14);ctx.lineTo(0,-r+(i%5===0?25:20));ctx.strokeStyle=i%5===0?getComputedStyle(document.body).getPropertyValue('--text'):getComputedStyle(document.body).getPropertyValue('--line');ctx.lineWidth=i%5===0?3:1;ctx.stroke();ctx.restore()}drawHand(ctx,(d.getHours()%12+d.getMinutes()/60)*Math.PI/6,r*.52,5);drawHand(ctx,(d.getMinutes()+d.getSeconds()/60)*Math.PI/30,r*.72,4);drawHand(ctx,d.getSeconds()*Math.PI/30,r*.78,2,getComputedStyle(document.body).getPropertyValue('--accent'));ctx.restore()}
function drawHand(ctx,a,len,w,color){ctx.save();ctx.rotate(a);ctx.beginPath();ctx.moveTo(0,5);ctx.lineTo(0,-len);ctx.strokeStyle=color||getComputedStyle(document.body).getPropertyValue('--text');ctx.lineWidth=w;ctx.lineCap='round';ctx.stroke();ctx.restore()}
function applyTheme(){document.body.classList.toggle('dark',state.dark);$('darkToggle').checked=state.dark}
function update(){if(state.detail){renderDetailClock();return}renderHeader();renderMap();renderSchedule();renderNext();renderTimetable();renderFavorites();renderNews();renderBanner();renderClock();const t=timeStr(now());$('positionUpdated').textContent='更新 '+t;$('lastUpdated').textContent='更新 '+t;$('heroSub').textContent=`${line().name}・${line().stations[state.stationIndex]}駅・${state.direction==='up'?'上り':'下り'}を表示中`;save()}

async function findTrain(){const q=normalizeTrainNo($('trainNumberInput').value);if(!q){$('trainSearchResult').innerHTML='<span>列車番号を入力してください（例：1980S）</span>';return} $('trainSearchResult').innerHTML='<span>公式時刻表データを検索中…</span>'; await loadOfficialData(); const official=findOfficialTrain(q); if(official){ state.detail=officialToDetail(official,q); $('trainSearchResult').innerHTML=`<span>「${q}」を公式時刻表データから表示します。<span class="source-pill">${official.day==='holiday'?'土・休日':'平日'}</span></span>`; save(); showDetail(); return; } let train=trainDatabase[q]; if(!train){const base=trainForLine();train={type:state.type,code:base.code,cars:base.cars,origin:base.origin,destination:base.destination,state:'デモ時刻',notice:'公式PDF解析データに見つからないため、デモ時刻を表示しています。',stops:buildGeneratedDetailStops()};$('trainSearchResult').innerHTML=`<span>「${q}」は公式解析データに見つかりませんでした。デモ時刻を表示します。</span>`}else{$('trainSearchResult').innerHTML=`<span>「${q}」を登録データから表示します。</span>`}state.detail={...train,no:q,crew:train.crew||crewForRoute(train.route||line().name)};save();showDetail()}
function buildGeneratedDetailStops(){const l=line(),base=new Date();let start=state.direction==='up'?0:l.stations.length-1,arr=[];for(let i=0;i<l.stations.length;i++){const idx=state.direction==='up'?i:l.stations.length-1-i,d=new Date(base.getTime()+(i*5+2)*60000),a=`${pad(d.getHours())}:${pad(d.getMinutes())}:${pad((i*20)%60)}`,dep=`${pad(d.getHours())}:${pad(d.getMinutes())}:${pad((i*20+30)%60)}`;arr.push([l.stations[idx],a,dep])}return arr}
function showDetail(){if(!state.detail)return;document.getElementById('listView').hidden=true;document.getElementById('detailView').hidden=false;document.querySelector('.bottom-nav').style.display='none';renderDetail();window.scrollTo({top:0,behavior:'instant'})}
function hideDetail(){state.detail=null;document.getElementById('detailView').hidden=true;document.getElementById('listView').hidden=false;document.querySelector('.bottom-nav').style.display='grid';$('trainNumberInput').value='';save();update();window.scrollTo({top:0,behavior:'smooth'})}
function renderDetail(){const t=state.detail;t.crew=t.crew||crewForRoute(t.route||line().name);$('detailType').textContent=t.type;$('detailCode').textContent=t.code;$('detailCars').textContent=t.cars;$('detailOrigin').textContent=t.origin;$('detailDestination').textContent=t.destination;$('detailTrainNo').textContent=t.no;$('detailCrewName').textContent=t.crew||'名古屋乗務区';$('detailCrewState').textContent=t.state||'乗務開始';$('detailNotice').innerHTML=(t.notice||'')+(t.source?`<br><a href="${t.source}" target="_blank" rel="noopener">公式PDFを開く ↗</a>`:'');$('detailDate').textContent=timeStr(now(),true)+'　'+now().toLocaleDateString('ja-JP',{month:'numeric',day:'numeric',weekday:'short'});$('detailSchedule').innerHTML=t.stops.map((s,i)=>`<tr class="${i===0?'detail-current':''}"><td class="row-mark">${i===0?'●':''}</td><td>${s[0]}</td><td>${s[1]}</td><td>${s[2]}</td></tr>`).join('');renderDetailClock()}
function renderDetailClock(){if(!state.detail)return;const d=now();$('detailDigital').textContent=timeStr(d,true);drawClock($('detailAnalog'),d);$('detailDate').textContent=timeStr(d,true)+'　'+d.toLocaleDateString('ja-JP',{month:'numeric',day:'numeric',weekday:'short'})}
function bind(){
 $('lineSelect').onchange=e=>setLine(e.target.value);$('stationSelect').onchange=e=>{state.stationIndex=+e.target.value;update()};$('directionSelect').onchange=e=>{state.direction=e.target.value;update()};$('typeSelect').onchange=e=>{state.type=e.target.value;update()};
 $('trainSearchBtn').onclick=findTrain;$('trainNumberInput').onkeydown=e=>{if(e.key==='Enter')findTrain()};$('trainNumberInput').oninput=()=>{$('trainSearchResult').textContent=''};
 $('themeBtn').onclick=()=>{state.dark=!state.dark;applyTheme();update()};$('darkToggle').onchange=e=>{state.dark=e.target.checked;applyTheme();update()};$('secondsToggle').onchange=e=>{state.seconds=e.target.checked;update()};$('autoRefresh').onchange=e=>{state.auto=e.target.checked;save();toast(state.auto?'自動更新ON':'自動更新OFF')};$('notifyToggle').onchange=e=>{state.notify=e.target.checked;save();toast(state.notify?'通知デモON':'通知デモOFF')};$('refreshBtn').onclick=()=>{update();toast('表示を更新しました')};
 $('officialBtn').onclick=()=>window.open(OFFICIAL_URL,'_blank');$('officialMenu').onclick=()=>window.open(OFFICIAL_URL,'_blank');$('menuBtn').onclick=()=>{$('menuDialog').showModal()};$('closeDialog').onclick=()=>$('menuDialog').close();$('simulateDelay').onclick=()=>{state.delay=true;update();$('menuDialog').close();toast('遅延デモON')};$('clearDelay').onclick=()=>{state.delay=false;state.cancel=false;update();$('menuDialog').close();toast('平常運転に戻しました')};$('simulateCancel').onclick=()=>{state.cancel=true;update();$('menuDialog').close();toast('運休デモON')};
 $('favoriteStation').onclick=()=>toggleFavorite(line().stations[state.stationIndex]);$('clearFavorites').onclick=()=>{state.favorites=[];renderFavorites();renderSchedule();save();toast('お気に入りを消去しました')};
 document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;document.querySelectorAll('#scheduleTable tbody tr').forEach((r,i)=>{r.style.display=f==='all'||(f==='local'&&state.type==='普通')||(f==='favorite'&&state.favorites.includes(line().stations[i]))||(f==='delay'&&state.delay)?'':'none'})});
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('.table-wrap').classList.toggle('compact',state.view==='compact')});
 document.querySelectorAll('.nav-item[data-target]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.target)?.scrollIntoView({behavior:'smooth',block:'start'}));$('stationBtn').onclick=()=>{$('stationSelect').focus();window.scrollTo({top:150,behavior:'smooth'})};$('settingsBtn').onclick=()=>$('settingsPanel').scrollIntoView({behavior:'smooth',block:'center'});
 $('shareBtn').onclick=async()=>{try{if(navigator.share)await navigator.share({title:'MEITETSU Operation Web',text:`${line().name} ${line().stations[state.stationIndex]}駅`,url:location.href});else{await navigator.clipboard.writeText(location.href);toast('URLをコピーしました')}}catch(e){}};
 $('fullscreenBtn').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch(e){toast('全画面表示に対応していない環境です')}};
 $('searchStation').oninput=searchStation;$('searchStation').onkeydown=e=>{if(e.key==='Enter')searchStation()};$('searchStation').nextElementSibling.onclick=searchStation;
 $('backBtn').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});$('detailBack').onclick=hideDetail;$('detailTheme').onclick=()=>{state.dark=!state.dark;applyTheme();renderDetail()};$('detailZoomIn').onclick=()=>changeZoom(.1);$('detailZoomOut').onclick=()=>changeZoom(-.1);$('zoomIn').onclick=()=>changeZoom(.1);$('zoomOut').onclick=()=>changeZoom(-.1);$('detailMenu').onclick=()=>toast('列車詳細メニュー');
}
function changeZoom(delta){state.zoom=Math.min(1.3,Math.max(.8,(state.zoom||1)+delta));document.documentElement.style.setProperty('--zoom',state.zoom);save();toast(`表示倍率 ${Math.round(state.zoom*100)}%`)}
function searchStation(){const q=$('stationSearch').value.trim();if(!q){$('searchResult').innerHTML='';return}const out=[];for(const [k,l] of Object.entries(lines))l.stations.forEach((s,i)=>{if(s.includes(q))out.push(`<button class="search-result" data-k="${k}" data-i="${i}">${s}<small>${l.name}</small></button>`)});$('searchResult').innerHTML=out.length?out.join(''):'<div class="empty">該当駅なし</div>';document.querySelectorAll('.search-result').forEach(b=>b.onclick=()=>{state.line=b.dataset.k;state.stationIndex=+b.dataset.i;$('lineSelect').value=state.line;fillStations();renderQuick();$('menuDialog').close();update()})}
let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}else toast('Safariでは共有メニューから「ホーム画面に追加」を選べます')};
load();state.favorites=Array.isArray(state.favorites)?state.favorites:[];initSelectors();document.documentElement.style.setProperty('--zoom',state.zoom||1);applyTheme();bind();update();loadOfficialData();setInterval(()=>{if(state.detail)renderDetailClock();else if(state.auto)update();else renderClock()},1000);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
